variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GET_SOURCES_ATTEMPTS: 5
  GIT_STRATEGY: fetch
  IMAGE: rego.corp.nucleisys.com/software/build_toolchain
  IMAGE_TAG: "18.04"

default:
  tags:
    - env::docker
    - net::outside
  image: $IMAGE:$IMAGE_TAG

build_gcc_linux:
  stage: build
  interruptible: true
  parallel:
    matrix:
      - MODE: [ newlib, linux]
        TARGET: [ rv32imafdcbpv-ilp32d, rv64imafdcbpv-lp64d ]
  script:
    - if [ "x${MODE}" == "xlinux" ] ; then apt install -y python3 ; fi
    - bash scripts/build_linux_toolchain.sh
  artifacts:
    when: always
    name: "nuclei_${MODE}_${TARGET}_toolchain_${CI_COMMIT_SHORT_SHA}"
    paths:
      - nuclei_${MODE}_${TARGET}_toolchain_${CI_COMMIT_SHORT_SHA}.tar.gz
      - build.log